022-11-06 07:09:54.009 [debug] <0.5585.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2022-11-06 07:09:54.012 [debug] <0.5586.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2022-11-06 07:09:57.006 [debug] <0.5589.0> Supervisor {<0.5589.0>,rabbit_web_stomp_connection_sup} started rabbit_web_stomp_connection_sup:start_keepalive_link() at pid <0.5590.0>
2022-11-06 07:09:57.007 [debug] <0.5589.0> Supervisor {<0.5589.0>,rabbit_web_stomp_connection_sup} started cowboy_clear:start_link({acceptor,{0,0,0,0,0,0,0,0},61611}, ranch_tcp, #{env => #{dispatch => [{'_',[],[{[<<"ws">>],[],rabbit_web_stomp_handler,[{type,text},{ws_opts,...}]}]}],...},...}) at pid <0.5591.0>
2022-11-06 07:09:57.010 [debug] <0.5593.0> Supervisor {<0.5593.0>,amqp_connection_sup} started amqp_connection_type_sup:start_link() at pid <0.5594.0>
2022-11-06 07:09:57.010 [debug] <0.5593.0> Supervisor {<0.5593.0>,amqp_connection_sup} started amqp_gen_connection:start_link(<0.5594.0>, {amqp_params_direct,<<"user123">>,{encrypted,<<"sJnsMKpYb6jLMkJvoHrdHDm6R1wsqHxHzkVwsaDBKetsfeweKi...">>},...}) at pid <0.5595.0>
2022-11-06 07:09:57.010 [debug] <0.5596.0> User 'user123' failed authenticatation by backend rabbit_auth_backend_internal
2022-11-06 07:09:57.010 [debug] <0.5596.0> auth_backend_http: POST http://127.0.0.1:8080/rabbitmq/user
2022-11-06 07:09:57.011 [debug] <0.5596.0> auth_backend_http: request timeout: 15000, connection timeout: 15000
2022-11-06 07:09:57.011 [debug] <0.5596.0> User 'user123' failed authenticatation by backend rabbit_auth_backend_http
2022-11-06 07:09:57.011 [warning] <0.5591.0> STOMP login failed for user "user123"
2022-11-06 07:09:57.011 [error] <0.5591.0> STOMP error frame sent:
Message: "Bad CONNECT"
Detail: "Access refused for user 'user123'\n"
Server private detail: none
2022-11-06 07:09:57.021 [debug] <0.5598.0> Supervisor {<0.5598.0>,rabbit_web_stomp_connection_sup} started rabbit_web_stomp_connection_sup:start_keepalive_link() at pid <0.5599.0>
2022-11-06 07:09:57.021 [debug] <0.5598.0> Supervisor {<0.5598.0>,rabbit_web_stomp_connection_sup} started cowboy_clear:start_link({acceptor,{0,0,0,0,0,0,0,0},61611}, ranch_tcp, #{env => #{dispatch => [{'_',[],[{[<<"ws">>],[],rabbit_web_stomp_handler,[{type,text},{ws_opts,...}]}]}],...},...}) at pid <0.5600.0>
2022-11-06 07:09:57.022 [debug] <0.5602.0> Supervisor {<0.5602.0>,amqp_connection_sup} started amqp_connection_type_sup:start_link() at pid <0.5603.0>
2022-11-06 07:09:57.022 [debug] <0.5602.0> Supervisor {<0.5602.0>,amqp_connection_sup} started amqp_gen_connection:start_link(<0.5603.0>, {amqp_params_direct,<<"user123">>,{encrypted,<<"tzZMNWr2U/+CGLMP2bIphlSw/BzoLbZGhYTkN7MbhkRdEvipBT...">>},...}) at pid <0.5604.0>
2022-11-06 07:09:57.023 [debug] <0.5605.0> User 'user123' failed authenticatation by backend rabbit_auth_backend_internal
2022-11-06 07:09:57.023 [debug] <0.5605.0> auth_backend_http: POST http://127.0.0.1:8080/rabbitmq/user
2022-11-06 07:09:57.023 [debug] <0.5605.0> auth_backend_http: request timeout: 15000, connection timeout: 15000
2022-11-06 07:09:57.023 [debug] <0.5605.0> User 'user123' failed authenticatation by backend rabbit_auth_backend_http
2022-11-06 07:09:57.023 [warning] <0.5600.0> STOMP login failed for user "user123"
2022-11-06 07:09:57.023 [error] <0.5600.0> STOMP error frame sent:
Message: "Bad CONNECT"
Detail: "Access refused for user 'user123'\n"
Server private detail: none

2022-11-06 07:44:30.355 [debug] <0.1417.0> Supervisor {<0.1417.0>,amqp_connection_sup} started amqp_gen_connection:start_link(<0.1418.0>, {amqp_params_direct,<<"test_user123">>,{encrypted,<<"e7eCV7IDHLkoi5pSE5CJ3zfsGv9xp4lElSgLVhLwIj/9q...">>},...}) at pid <0.1419.0>
2022-11-06 07:44:30.355 [debug] <0.1420.0> User 'test_user123' failed authenticatation by backend rabbit_auth_backend_internal
2022-11-06 07:44:30.355 [error] <0.1415.0> STOMP error frame sent:
Message: "Processing error"
Detail: "Processing error"
Server private detail: {{case_clause,{error,{{'EXIT',{{badmatch,false},[{rabbit_auth_backend_http,do_http_req,2,[{file,"src/rabbit_auth_backend_http.erl"},{line,129}]},{rabbit_auth_backend_http,http_req,3,[{file,"src/rabbit_auth_backend_http.erl"},{line,116}]},{rabbit_auth_backend_http,user_login_authentication,2,[{file,"src/rabbit_auth_backend_http.erl"},{line,36}]},{rabbit_access_control,try_authenticate,3,[{file,"src/rabbit_access_control.erl"},{line,85}]},{rabbit_access_control,'-check_user_login/2-fun-0-',4,[{file,"src/rabbit_access_control.erl"},{line,56}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{rabbit_direct,connect,5,[{file,"src/rabbit_direct.erl"},{line,92}]}]}},rabbit@7a3ebc5c9688}}},[{rabbit_stomp_processor,do_login,7,[{file,"src/rabbit_stomp_processor.erl"},{line,586}]},{rabbit_stomp_processor,'-process_connect/3-fun-0-',6,[{file,"src/rabbit_stomp_processor.erl"},{line,275}]},{rabbit_stomp_processor,process_request,3,[{file,"src/rabbit_stomp_processor.erl"},{line,232}]},{rabbit_web_stomp_handler,handle_data1,2,[{file,"src/rabbit_web_stomp_handler.erl"},{line,275}]},{rabbit_web_stomp_handler,handle_data,2,[{file,"src/rabbit_web_stomp_handler.erl"},{line,256}]},{cowboy_websocket,handler_call,6,[{file,"src/cowboy_websocket.erl"},{line,528}]},{cowboy_http,loop,1,[{file,"src/cowboy_http.erl"},{line,254}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2022-11-06 07:44:30.359 [debug] <0.1421.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2022-11-06 07:44:30.365 [debug] <0.1423.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2022-11-06 07:44:30.368 [debug] <0.1424.0> Supervisor {<0.1424.0>,rabbit_web_stomp_connection_sup} started rabbit_web_stomp_connection_sup:start_keepalive_link() at pid <0.1425.0>
2022-11-06 07:44:30.368 [debug] <0.1424.0> Supervisor {<0.1424.0>,rabbit_web_stomp_connection_sup} started cowboy_clear:start_link({acceptor,{0,0,0,0,0,0,0,0},61611}, ranch_tcp, #{env => #{dispatch => [{'_',[],[{[<<"ws">>],[],rabbit_web_stomp_handler,[{type,text},{ws_opts,...}]}]}],...},...}) at pid <0.1426.0>
2022-11-06 07:44:30.369 [debug] <0.1428.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2022-11-06 07:44:30.369 [debug] <0.1429.0> Supervisor {<0.1429.0>,amqp_connection_sup} started amqp_connection_type_sup:start_link() at pid <0.1430.0>
2022-11-06 07:44:30.369 [debug] <0.1429.0> Supervisor {<0.1429.0>,amqp_connection_sup} started amqp_gen_connection:start_link(<0.1430.0>, {amqp_params_direct,<<"test_user123">>,{encrypted,<<"Oe6XPCNnA6EhDwf8pj3LaNLnFZGajq7LVQxmQ72HP/Jw4...">>},...}) at pid <0.1432.0>
2022-11-06 07:44:30.369 [debug] <0.1433.0> User 'test_user123' failed authenticatation by backend rabbit_auth_backend_internal
2022-11-06 07:44:30.370 [error] <0.1426.0> STOMP error frame sent:
Message: "Processing error"
Detail: "Processing error"
Server private detail: {{case_clause,{error,{{'EXIT',{{badmatch,false},[{rabbit_auth_backend_http,do_http_req,2,[{file,"src/rabbit_auth_backend_http.erl"},{line,129}]},{rabbit_auth_backend_http,http_req,3,[{file,"src/rabbit_auth_backend_http.erl"},{line,116}]},{rabbit_auth_backend_http,user_login_authentication,2,[{file,"src/rabbit_auth_backend_http.erl"},{line,36}]},{rabbit_access_control,try_authenticate,3,[{file,"src/rabbit_access_control.erl"},{line,85}]},{rabbit_access_control,'-check_user_login/2-fun-0-',4,[{file,"src/rabbit_access_control.erl"},{line,56}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{rabbit_direct,connect,5,[{file,"src/rabbit_direct.erl"},{line,92}]}]}},rabbit@7a3ebc5c9688}}},[{rabbit_stomp_processor,do_login,7,[{file,"src/rabbit_stomp_processor.erl"},{line,586}]},{rabbit_stomp_processor,'-process_connect/3-fun-0-',6,[{file,"src/rabbit_stomp_processor.erl"},{line,275}]},{rabbit_stomp_processor,process_request,3,[{file,"src/rabbit_stomp_processor.erl"},{line,232}]},{rabbit_web_stomp_handler,handle_data1,2,[{file,"src/rabbit_web_stomp_handler.erl"},{line,275}]},{rabbit_web_stomp_handler,handle_data,2,[{file,"src/rabbit_web_stomp_handler.erl"},{line,256}]},{cowboy_websocket,handler_call,6,[{file,"src/cowboy_websocket.erl"},{line,528}]},{cowboy_http,loop,1,[{file,"src/cowboy_http.erl"},{line,254}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
